#!/usr/bin/env python3
"""
Import Trinity Cata `playercreateinfo*` starter data from firelands-cata-ref.

Emits:
  sql/migrations/42_world_playercreateinfo_tables.sql
  sql/migrations/43_world_playercreateinfo_data.sql

Usage:
  python3 tools/sql/import_ref_playercreateinfo.py
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[2]
_TOOLS_SQL = Path(__file__).resolve().parent
if str(_TOOLS_SQL) not in sys.path:
    sys.path.insert(0, str(_TOOLS_SQL))

from import_ref_creature_data import extract_insert_rows  # noqa: E402


def append_batched(
    lines: list[str], stmt_prefix: str, rows: list[str], batch_size: int
) -> None:
    for i in range(0, len(rows), batch_size):
        chunk = rows[i : i + batch_size]
        lines.append(stmt_prefix)
        lines.append(",\n".join(chunk) + ";")
        lines.append("")

TABLES_SQL = """\
-- Starter character world data (spawn, spells, skills). Generated by tools/sql/import_ref_playercreateinfo.py
USE `firelands_world`;

CREATE TABLE IF NOT EXISTS `playercreateinfo` (
  `race` tinyint unsigned NOT NULL DEFAULT 0,
  `class` tinyint unsigned NOT NULL DEFAULT 0,
  `map` smallint unsigned NOT NULL DEFAULT 0,
  `zone` int unsigned NOT NULL DEFAULT 0,
  `position_x` float NOT NULL DEFAULT 0,
  `position_y` float NOT NULL DEFAULT 0,
  `position_z` float NOT NULL DEFAULT 0,
  `orientation` float NOT NULL DEFAULT 0,
  PRIMARY KEY (`race`,`class`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `playercreateinfo_spell`;
DROP TABLE IF EXISTS `playercreateinfo_skill`;

CREATE TABLE `playercreateinfo_spell` (
  `raceMask` int unsigned NOT NULL DEFAULT 0,
  `classMask` int unsigned NOT NULL DEFAULT 0,
  `spellId` int unsigned NOT NULL,
  PRIMARY KEY (`raceMask`,`classMask`,`spellId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `playercreateinfo_skill` (
  `raceMask` int unsigned NOT NULL DEFAULT 0,
  `classMask` int unsigned NOT NULL DEFAULT 0,
  `skillId` smallint unsigned NOT NULL,
  `rank` smallint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`raceMask`,`classMask`,`skillId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
"""

DATA_SCHEMA_PREAMBLE = """\
DROP TABLE IF EXISTS `playercreateinfo_spell`;
DROP TABLE IF EXISTS `playercreateinfo_skill`;

CREATE TABLE `playercreateinfo_spell` (
  `raceMask` int unsigned NOT NULL DEFAULT 0,
  `classMask` int unsigned NOT NULL DEFAULT 0,
  `spellId` int unsigned NOT NULL,
  PRIMARY KEY (`raceMask`,`classMask`,`spellId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `playercreateinfo_skill` (
  `raceMask` int unsigned NOT NULL DEFAULT 0,
  `classMask` int unsigned NOT NULL DEFAULT 0,
  `skillId` smallint unsigned NOT NULL,
  `rank` smallint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`raceMask`,`classMask`,`skillId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
"""


def map_playercreateinfo_row(fields: list[str]) -> str:
    if len(fields) != 8:
        raise ValueError(f"playercreateinfo expected 8 fields, got {len(fields)}")
    return ",".join(fields)


def map_spell_row(fields: list[str]) -> str:
    if len(fields) < 3:
        raise ValueError("playercreateinfo_spell_custom row too short")
    race_mask, class_mask, spell_id = fields[0], fields[1], fields[2]
    return f"{race_mask},{class_mask},{spell_id}"


def map_skill_row(fields: list[str]) -> str:
    if len(fields) < 4:
        raise ValueError("playercreateinfo_skills row too short")
    race_mask, class_mask, skill_id, rank = fields[0], fields[1], fields[2], fields[3]
    return f"{race_mask},{class_mask},{skill_id},{rank}"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--ref",
        type=Path,
        default=_REPO_ROOT / "firelands-cata-ref" / "data" / "sql" / "base" / "db_world",
    )
    parser.add_argument(
        "--tables-out",
        type=Path,
        default=_REPO_ROOT / "sql" / "migrations" / "42_world_playercreateinfo_tables.sql",
    )
    parser.add_argument(
        "--data-out",
        type=Path,
        default=_REPO_ROOT / "sql" / "migrations" / "43_world_playercreateinfo_data.sql",
    )
    args = parser.parse_args()

    ref = args.ref
    spawn_rows = [
        map_playercreateinfo_row(r)
        for r in extract_insert_rows(ref / "playercreateinfo.sql", "playercreateinfo")
    ]
    spell_rows = [
        map_spell_row(r)
        for r in extract_insert_rows(
            ref / "playercreateinfo_spell_custom.sql", "playercreateinfo_spell_custom"
        )
    ]
    skill_rows = [
        map_skill_row(r)
        for r in extract_insert_rows(ref / "playercreateinfo_skills.sql", "playercreateinfo_skills")
    ]

    args.tables_out.parent.mkdir(parents=True, exist_ok=True)
    args.tables_out.write_text(TABLES_SQL, encoding="utf-8")

    lines: list[str] = [
        "-- Starter spawn / spells / skills from firelands-cata-ref (Trinity 4.3.4).",
        "USE `firelands_world`;",
        "",
        DATA_SCHEMA_PREAMBLE.strip(),
        "",
        "DELETE FROM `playercreateinfo`;",
        "",
    ]
    append_batched(
        lines,
        "REPLACE INTO `playercreateinfo` "
        "(`race`,`class`,`map`,`zone`,`position_x`,`position_y`,`position_z`,`orientation`) VALUES",
        [f"({r})" for r in spawn_rows],
        batch_size=80,
    )
    append_batched(
        lines,
        "REPLACE INTO `playercreateinfo_spell` (`raceMask`,`classMask`,`spellId`) VALUES",
        [f"({r})" for r in spell_rows],
        batch_size=120,
    )
    append_batched(
        lines,
        "REPLACE INTO `playercreateinfo_skill` (`raceMask`,`classMask`,`skillId`,`rank`) VALUES",
        [f"({r})" for r in skill_rows],
        batch_size=120,
    )
    args.data_out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {args.tables_out} and {args.data_out}")
    print(f"  playercreateinfo: {len(spawn_rows)} rows")
    print(f"  playercreateinfo_spell: {len(spell_rows)} rows")
    print(f"  playercreateinfo_skill: {len(skill_rows)} rows")


if __name__ == "__main__":
    main()
