#ifndef FIRELANDS_SHARED_NETWORK_WORLD_OPCODES_H
#define FIRELANDS_SHARED_NETWORK_WORLD_OPCODES_H

#include <shared/Common.h>

namespace Firelands {

// Opcodes aligned with build 15595 (Cataclysm 4.3.4):
// The-Cataclysm-Preservation-Project/TrinityCore Opcodes.h (OpcodeClient ~L385,
// OpcodeServer for SMSG_*), and firelands-cata-ref.
enum WorldOpcode : uint32 {
  SMSG_AUTH_CHALLENGE = 0x4542,
  CMSG_AUTH_SESSION = 0x0449,
  SMSG_AUTH_RESPONSE = 0x5DB6,
  SMSG_ADDON_INFO = 0x2C14,
  SMSG_CLIENTCACHE_VERSION = 0x2734,
  SMSG_TUTORIAL_FLAGS = 0x0B35,
  SMSG_FEATURE_SYSTEM_STATUS = 0x3DB7,
  /// Reference: SMSG_CONNECT_TO
  SMSG_CONNECT_TO = 0x0942,

  /// Reference: CMSG_ENUM_CHARACTERS
  CMSG_CHAR_ENUM = 0x0502,
  /// Reference: SMSG_ENUM_CHARACTERS_RESULT
  SMSG_CHAR_ENUM = 0x10B0,
  CMSG_CHAR_CREATE = 0x4A36,
  /// Reference: SMSG_CREATE_CHAR
  SMSG_CHAR_CREATE = 0x2D05,
  CMSG_CHAR_DELETE = 0x6425,
  /// Reference: SMSG_DELETE_CHAR
  SMSG_CHAR_DELETE = 0x0304,
  CMSG_PLAYER_LOGIN = 0x05B1,
  SMSG_LOGIN_VERIFY_WORLD = 0x2005,
  SMSG_TIME_SYNC_REQ = 0x3CA4,
  /// Reference: SMSG_STOP_MIRROR_TIMER (not used for spell book in 4.3.4).
  SMSG_STOP_MIRROR_TIMER = 0x0B06,
  SMSG_SEND_KNOWN_SPELLS = 0x0104,
  SMSG_SEND_UNLEARN_SPELLS = 0x4E25,
  /// Reference: SMSG_UPDATE_ACTION_BUTTONS
  SMSG_ACTION_BUTTONS = 0x38B5,
  SMSG_UPDATE_OBJECT = 0x4715,
  SMSG_MOTD = 0x0A35,
  SMSG_ACCOUNT_DATA_TIMES = 0x4B05,
  SMSG_REALM_SPLIT = 0x2714,
  SMSG_LOGIN_SET_TIME_SPEED = 0x4D15,
  SMSG_LEARNED_DANCE_MOVES = 0x0E05,
  /// Reference: SMSG_ACCOUNT_RESTRICTED_WARNING
  SMSG_ACCOUNT_RESTRICTED_WARNING = 0x51A7,
  /// Reference: SMSG_SET_DF_FAST_LAUNCH_RESULT
  SMSG_SET_DF_FAST_LAUNCH_RESULT = 0x35B6,
  SMSG_PONG = 0x4D42,
  /// Reference: SMSG_RAID_GROUP_ONLY (raid UI; not the same as legacy "initial raid error" names).
  SMSG_RAID_GROUP_ONLY = 0x0837,
  SMSG_INIT_WORLD_STATES = 0x4C15,
  SMSG_SETUP_CURRENCY = 0x15A5,
  SMSG_CLIENT_CONTROL_UPDATE = 0x2837,
  SMSG_BIND_POINT_UPDATE = 0x0527,
  SMSG_WORLD_SERVER_INFO = 0x31A2,
  SMSG_LOAD_CUF_PROFILES = 0x50B1,
  SMSG_SET_FORCED_REACTIONS = 0x4615,
  SMSG_SET_PROFICIENCY = 0x6207,
  SMSG_TALENTS_INFO = 0x6F26,
  SMSG_INITIALIZE_FACTIONS = 0x4634,
  MSG_SET_DUNGEON_DIFFICULTY = 0x4925,
  SMSG_HOTFIX_NOTIFY_BLOB = 0x19B5,
  SMSG_CONTACT_LIST = 0x6017,
  SMSG_ALL_ACHIEVEMENT_DATA = 0x58B1,
  SMSG_EQUIPMENT_SET_LIST = 0x2E04,
  /// Reference: TCPP OpcodeServer SMSG_QUERY_PLAYER_NAME_RESPONSE
  SMSG_QUERY_PLAYER_NAME_RESPONSE = 0x6E04,
  SMSG_QUERY_TIME_RESPONSE = 0x2124,
  SMSG_PLAYED_TIME = 0x6037,

  CMSG_PING = 0x444D,
  /// Reference: TCPP OpcodeClient CMSG_NAME_QUERY (Opcodes.h ~L385)
  CMSG_NAME_QUERY = 0x2224,
  CMSG_QUERY_TIME = 0x0A36,
  CMSG_PLAYED_TIME = 0x0804,

  MSG_MOVE_HEARTBEAT = 0x3914,
  MSG_MOVE_START_FORWARD = 0x7814,
  MSG_MOVE_START_BACKWARD = 0x330A,
  MSG_MOVE_STOP = 0x320A,
  MSG_MOVE_SET_FACING = 0x7914,

  /// Reference: CMSG_MESSAGECHAT_SAY (client uses one opcode per chat type).
  CMSG_MESSAGECHAT = 0x1154,
  SMSG_MESSAGECHAT = 0x2026,

  /// Reference: Opcodes.h (NPC gossip)
  CMSG_GOSSIP_HELLO = 0x4525,
  CMSG_GOSSIP_SELECT_OPTION = 0x0216,

  CMSG_READY_FOR_ACCOUNT_DATA_TIMES = 0x2B16,
  CMSG_REALM_SPLIT = 0x2906,
  CMSG_UPDATE_ACCOUNT_DATA = 0x4736,
  SMSG_UPDATE_ACCOUNT_DATA_COMPLETE = 0x2015,
  CMSG_LOG_DISCONNECT = 0x446D,
  CMSG_TIME_SYNC_RESP = 0x3B0C,
  CMSG_MOVE_TIME_SKIPPED = 0x7A0A,
  CMSG_LOADING_SCREEN_NOTIFY = 0x2422,
  CMSG_VIOLENCE_LEVEL = 0x7816,
};

} // namespace Firelands

#endif
