-- Starter character world data (spawn, spells, skills). Generated by tools/sql/import_ref_playercreateinfo.py
USE `firelands_world`;

CREATE TABLE IF NOT EXISTS `playercreateinfo` (
  `race` tinyint unsigned NOT NULL DEFAULT 0,
  `class` tinyint unsigned NOT NULL DEFAULT 0,
  `map` smallint unsigned NOT NULL DEFAULT 0,
  `zone` int unsigned NOT NULL DEFAULT 0,
  `position_x` float NOT NULL DEFAULT 0,
  `position_y` float NOT NULL DEFAULT 0,
  `position_z` float NOT NULL DEFAULT 0,
  `orientation` float NOT NULL DEFAULT 0,
  PRIMARY KEY (`race`,`class`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Drop legacy `race`/`class` schema if present; `IF NOT EXISTS` alone cannot migrate columns.
DROP TABLE IF EXISTS `playercreateinfo_spell`;
DROP TABLE IF EXISTS `playercreateinfo_skill`;

CREATE TABLE `playercreateinfo_spell` (
  `raceMask` int unsigned NOT NULL DEFAULT 0,
  `classMask` int unsigned NOT NULL DEFAULT 0,
  `spellId` int unsigned NOT NULL,
  PRIMARY KEY (`raceMask`,`classMask`,`spellId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `playercreateinfo_skill` (
  `raceMask` int unsigned NOT NULL DEFAULT 0,
  `classMask` int unsigned NOT NULL DEFAULT 0,
  `skillId` smallint unsigned NOT NULL,
  `rank` smallint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`raceMask`,`classMask`,`skillId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
