USE `firelands_world`;

-- creature_text seed data
-- Total entries: 24

INSERT INTO creature_text (creatureId, groupId, id, text, type, language, probability, emote, duration, sound, soundType, broadcastTextId, textRange, comment) VALUES (6, 0, 0, 'You no take candle!', 12, 0, 100, 0, 0, 0, 0, 16658, 0, 'Kobold Vermin - Random Say on Aggro');
INSERT INTO creature_text (creatureId, groupId, id, text, type, language, probability, emote, duration, sound, soundType, broadcastTextId, textRange, comment) VALUES (6, 0, 1, 'Yiieeeee! Me run!', 12, 7, 100, 0, 0, 0, 0, 1864, 0, 'Kobold Vermin - Random Say on Aggro');
INSERT INTO creature_text (creatureId, groupId, id, text, type, language, probability, emote, duration, sound, soundType, broadcastTextId, textRange, comment) VALUES (29, 1, 0, 'Let the battle for the Strand of the Ancients begin!', 41, 0, 100, 0, 0, 0, 0, 28844, 3, 'Kanrethad');
INSERT INTO creature_text (creatureId, groupId, id, text, type, language, probability, emote, duration, sound, soundType, broadcastTextId, textRange, comment) VALUES (29, 2, 0, 'Round 1 - Finished!', 41, 0, 100, 0, 0, 0, 0, 28989, 3, 'Kanrethad');
INSERT INTO creature_text (creatureId, groupId, id, text, type, language, probability, emote, duration, sound, soundType, broadcastTextId, textRange, comment) VALUES (38, 0, 0, 'The Brotherhood will not tolerate your actions.', 12, 7, 100, 0, 0, 0, 0, 1866, 0, 'Defias Thug - Random Say on Aggro');
INSERT INTO creature_text (creatureId, groupId, id, text, type, language, probability, emote, duration, sound, soundType, broadcastTextId, textRange, comment) VALUES (38, 0, 1, 'Ah, a chance to use this freshly sharpened blade.', 12, 7, 100, 0, 0, 0, 0, 1865, 0, 'Defias Thug - Random Say on Aggro');
INSERT INTO creature_text (creatureId, groupId, id, text, type, language, probability, emote, duration, sound, soundType, broadcastTextId, textRange, comment) VALUES (38, 0, 2, 'Feel the power of the Brotherhood!', 12, 7, 100, 0, 0, 0, 0, 1867, 0, 'Defias Thug - Random Say on Aggro');
INSERT INTO creature_text (creatureId, groupId, id, text, type, language, probability, emote, duration, sound, soundType, broadcastTextId, textRange, comment) VALUES (40, 0, 0, 'You no take candle!', 12, 0, 100, 0, 0, 0, 0, 16658, 0, 'Kobold Miner - Random Say on Aggro');
INSERT INTO creature_text (creatureId, groupId, id, text, type, language, probability, emote, duration, sound, soundType, broadcastTextId, textRange, comment) VALUES (61, 0, 0, 'The Brotherhood will not tolerate your actions.', 12, 7, 100, 0, 0, 0, 0, 1866, 0, 'Thuros Lightfingers - Random Say on Aggro');
INSERT INTO creature_text (creatureId, groupId, id, text, type, language, probability, emote, duration, sound, soundType, broadcastTextId, textRange, comment) VALUES (61, 0, 1, 'Ah, a chance to use this freshly sharpened blade.', 12, 7, 100, 0, 0, 0, 0, 1865, 0, 'Thuros Lightfingers - Random Say on Aggro');
INSERT INTO creature_text (creatureId, groupId, id, text, type, language, probability, emote, duration, sound, soundType, broadcastTextId, textRange, comment) VALUES (61, 0, 2, 'Feel the power of the Brotherhood!', 12, 7, 100, 0, 0, 0, 0, 1867, 0, 'Thuros Lightfingers - Random Say on Aggro');
INSERT INTO creature_text (creatureId, groupId, id, text, type, language, probability, emote, duration, sound, soundType, broadcastTextId, textRange, comment) VALUES (68, 2, 0, '%s throws a rotten apple at $n.', 16, 0, 100, 0, 0, 0, 0, 31671, 0, 'Stormwind City Guard');
INSERT INTO creature_text (creatureId, groupId, id, text, type, language, probability, emote, duration, sound, soundType, broadcastTextId, textRange, comment) VALUES (68, 3, 0, '%s throws rotten banana on $n.', 16, 0, 100, 0, 0, 0, 0, 31672, 0, 'Stormwind City Guard');
INSERT INTO creature_text (creatureId, groupId, id, text, type, language, probability, emote, duration, sound, soundType, broadcastTextId, textRange, comment) VALUES (68, 4, 0, '%s spits on $n.', 16, 0, 100, 0, 0, 0, 0, 31673, 0, 'Stormwind City Guard');
INSERT INTO creature_text (creatureId, groupId, id, text, type, language, probability, emote, duration, sound, soundType, broadcastTextId, textRange, comment) VALUES (68, 5, 0, 'Monster!', 12, 0, 100, 0, 0, 0, 0, 31662, 0, 'Stormwind City Guard');
INSERT INTO creature_text (creatureId, groupId, id, text, type, language, probability, emote, duration, sound, soundType, broadcastTextId, textRange, comment) VALUES (68, 5, 1, 'Murderer!', 12, 0, 100, 0, 0, 0, 0, 31679, 0, 'Stormwind City Guard');
INSERT INTO creature_text (creatureId, groupId, id, text, type, language, probability, emote, duration, sound, soundType, broadcastTextId, textRange, comment) VALUES (68, 5, 2, 'GET A ROPE!', 12, 0, 100, 0, 0, 0, 0, 31669, 0, 'Stormwind City Guard');
INSERT INTO creature_text (creatureId, groupId, id, text, type, language, probability, emote, duration, sound, soundType, broadcastTextId, textRange, comment) VALUES (68, 5, 3, 'How dare you set foot in our city!', 12, 0, 100, 0, 0, 0, 0, 31684, 0, 'Stormwind City Guard');
INSERT INTO creature_text (creatureId, groupId, id, text, type, language, probability, emote, duration, sound, soundType, broadcastTextId, textRange, comment) VALUES (68, 5, 4, 'You disgust me.', 12, 0, 100, 0, 0, 0, 0, 31680, 0, 'Stormwind City Guard');
INSERT INTO creature_text (creatureId, groupId, id, text, type, language, probability, emote, duration, sound, soundType, broadcastTextId, textRange, comment) VALUES (68, 5, 5, 'Looks like we''re going to have ourselves an execution.', 12, 0, 100, 0, 0, 0, 0, 31682, 0, 'Stormwind City Guard');
INSERT INTO creature_text (creatureId, groupId, id, text, type, language, probability, emote, duration, sound, soundType, broadcastTextId, textRange, comment) VALUES (68, 5, 6, 'Traitorous dog.', 12, 0, 100, 0, 0, 0, 0, 31665, 0, 'Stormwind City Guard');
INSERT INTO creature_text (creatureId, groupId, id, text, type, language, probability, emote, duration, sound, soundType, broadcastTextId, textRange, comment) VALUES (68, 5, 7, 'My family was wiped out by the Scourge! MONSTER!', 12, 0, 100, 0, 0, 0, 0, 31667, 0, 'Stormwind City Guard');
INSERT INTO creature_text (creatureId, groupId, id, text, type, language, probability, emote, duration, sound, soundType, broadcastTextId, textRange, comment) VALUES (80, 0, 0, 'You no take candle!', 12, 0, 50, 0, 0, 0, 0, 1868, 0, 'combat Say');
INSERT INTO creature_text (creatureId, groupId, id, text, type, language, probability, emote, duration, sound, soundType, broadcastTextId, textRange, comment) VALUES (80, 0, 1, 'Yiieeeee! Me run!', 12, 0, 50, 0, 0, 0, 0, 1864, 0, 'combat Say');
