CREATE DATABASE IF NOT EXISTS `firelands_world`;
USE `firelands_world`;

CREATE TABLE IF NOT EXISTS `version` (
  `coreVersion` varchar(120) NOT NULL,
  `dbVersion` varchar(120) DEFAULT NULL,
  PRIMARY KEY (`coreVersion`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `gossip_menu` (
  `menuId` int unsigned NOT NULL DEFAULT '0',
  `textId` int unsigned NOT NULL DEFAULT '0',
  `verifiedBuild` smallint NOT NULL DEFAULT '0',
  PRIMARY KEY (`menuId`, `textId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `npc_text` (
  `id` int unsigned NOT NULL DEFAULT '0',
  `text0_0` longtext,
  `text0_1` longtext,
  `broadcastTextId0` int NOT NULL DEFAULT '0',
  `lang0` tinyint unsigned NOT NULL DEFAULT '0',
  `probability0` float NOT NULL DEFAULT '0',
  `emoteDelay0_0` smallint unsigned NOT NULL DEFAULT '0',
  `emote0_0` smallint unsigned NOT NULL DEFAULT '0',
  `emoteDelay0_1` smallint unsigned NOT NULL DEFAULT '0',
  `emote0_1` smallint unsigned NOT NULL DEFAULT '0',
  `emoteDelay0_2` smallint unsigned NOT NULL DEFAULT '0',
  `emote0_2` smallint unsigned NOT NULL DEFAULT '0',
  `text1_0` longtext,
  `text1_1` longtext,
  `broadcastTextId1` int NOT NULL DEFAULT '0',
  `lang1` tinyint unsigned NOT NULL DEFAULT '0',
  `probability1` float NOT NULL DEFAULT '0',
  `emoteDelay1_0` smallint unsigned NOT NULL DEFAULT '0',
  `emote1_0` smallint unsigned NOT NULL DEFAULT '0',
  `emoteDelay1_1` smallint unsigned NOT NULL DEFAULT '0',
  `emote1_1` smallint unsigned NOT NULL DEFAULT '0',
  `emoteDelay1_2` smallint unsigned NOT NULL DEFAULT '0',
  `emote1_2` smallint unsigned NOT NULL DEFAULT '0',
  `text2_0` longtext,
  `text2_1` longtext,
  `broadcastTextId2` int NOT NULL DEFAULT '0',
  `lang2` tinyint unsigned NOT NULL DEFAULT '0',
  `probability2` float NOT NULL DEFAULT '0',
  `emoteDelay2_0` smallint unsigned NOT NULL DEFAULT '0',
  `emote2_0` smallint unsigned NOT NULL DEFAULT '0',
  `emoteDelay2_1` smallint unsigned NOT NULL DEFAULT '0',
  `emote2_1` smallint unsigned NOT NULL DEFAULT '0',
  `emoteDelay2_2` smallint unsigned NOT NULL DEFAULT '0',
  `emote2_2` smallint unsigned NOT NULL DEFAULT '0',
  `text3_0` longtext,
  `text3_1` longtext,
  `broadcastTextId3` int NOT NULL DEFAULT '0',
  `lang3` tinyint unsigned NOT NULL DEFAULT '0',
  `probability3` float NOT NULL DEFAULT '0',
  `emoteDelay3_0` smallint unsigned NOT NULL DEFAULT '0',
  `emote3_0` smallint unsigned NOT NULL DEFAULT '0',
  `emoteDelay3_1` smallint unsigned NOT NULL DEFAULT '0',
  `emote3_1` smallint unsigned NOT NULL DEFAULT '0',
  `emoteDelay3_2` smallint unsigned NOT NULL DEFAULT '0',
  `emote3_2` smallint unsigned NOT NULL DEFAULT '0',
  `text4_0` longtext,
  `text4_1` longtext,
  `broadcastTextId4` int NOT NULL DEFAULT '0',
  `lang4` tinyint unsigned NOT NULL DEFAULT '0',
  `probability4` float NOT NULL DEFAULT '0',
  `emoteDelay4_0` smallint unsigned NOT NULL DEFAULT '0',
  `emote4_0` smallint unsigned NOT NULL DEFAULT '0',
  `emoteDelay4_1` smallint unsigned NOT NULL DEFAULT '0',
  `emote4_1` smallint unsigned NOT NULL DEFAULT '0',
  `emoteDelay4_2` smallint unsigned NOT NULL DEFAULT '0',
  `emote4_2` smallint unsigned NOT NULL DEFAULT '0',
  `text5_0` longtext,
  `text5_1` longtext,
  `broadcastTextId5` int NOT NULL DEFAULT '0',
  `lang5` tinyint unsigned NOT NULL DEFAULT '0',
  `probability5` float NOT NULL DEFAULT '0',
  `emoteDelay5_0` smallint unsigned NOT NULL DEFAULT '0',
  `emote5_0` smallint unsigned NOT NULL DEFAULT '0',
  `emoteDelay5_1` smallint unsigned NOT NULL DEFAULT '0',
  `emote5_1` smallint unsigned NOT NULL DEFAULT '0',
  `emoteDelay5_2` smallint unsigned NOT NULL DEFAULT '0',
  `emote5_2` smallint unsigned NOT NULL DEFAULT '0',
  `text6_0` longtext,
  `text6_1` longtext,
  `broadcastTextId6` int NOT NULL DEFAULT '0',
  `lang6` tinyint unsigned NOT NULL DEFAULT '0',
  `probability6` float NOT NULL DEFAULT '0',
  `emoteDelay6_0` smallint unsigned NOT NULL DEFAULT '0',
  `emote6_0` smallint unsigned NOT NULL DEFAULT '0',
  `emoteDelay6_1` smallint unsigned NOT NULL DEFAULT '0',
  `emote6_1` smallint unsigned NOT NULL DEFAULT '0',
  `emoteDelay6_2` smallint unsigned NOT NULL DEFAULT '0',
  `emote6_2` smallint unsigned NOT NULL DEFAULT '0',
  `text7_0` longtext,
  `text7_1` longtext,
  `broadcastTextId7` int NOT NULL DEFAULT '0',
  `lang7` tinyint unsigned NOT NULL DEFAULT '0',
  `probability7` float NOT NULL DEFAULT '0',
  `emoteDelay7_0` smallint unsigned NOT NULL DEFAULT '0',
  `emote7_0` smallint unsigned NOT NULL DEFAULT '0',
  `emoteDelay7_1` smallint unsigned NOT NULL DEFAULT '0',
  `emote7_1` smallint unsigned NOT NULL DEFAULT '0',
  `emoteDelay7_2` smallint unsigned NOT NULL DEFAULT '0',
  `emote7_2` smallint unsigned NOT NULL DEFAULT '0',
  `verifiedBuild` int DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `schema_migrations` (
  `migration` varchar(255) NOT NULL,
  `appliedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`migration`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;