USE `firelands_world`;

CREATE TABLE IF NOT EXISTS `quest_template` (
  `id` int unsigned NOT NULL DEFAULT '0',
  `questType` tinyint unsigned NOT NULL DEFAULT '2',
  `questLevel` smallint NOT NULL DEFAULT '1',
  `minLevel` smallint NOT NULL DEFAULT '0',
  `questSortId` smallint NOT NULL DEFAULT '0',
  `questInfoId` smallint unsigned NOT NULL DEFAULT '0',
  `suggestedGroupNum` tinyint unsigned NOT NULL DEFAULT '0',
  `requiredFactionId1` smallint unsigned NOT NULL DEFAULT '0',
  `requiredFactionId2` smallint unsigned NOT NULL DEFAULT '0',
  `requiredFactionValue1` int NOT NULL DEFAULT '0',
  `requiredFactionValue2` int NOT NULL DEFAULT '0',
  `rewardNextQuest` int unsigned NOT NULL DEFAULT '0',
  `rewardXpDifficulty` tinyint unsigned NOT NULL DEFAULT '0',
  `rewardMoney` int NOT NULL DEFAULT '0',
  `rewardBonusMoney` int unsigned NOT NULL DEFAULT '0',
  `rewardDisplaySpell` int unsigned NOT NULL DEFAULT '0',
  `rewardSpell` int NOT NULL DEFAULT '0',
  `rewardHonor` int NOT NULL DEFAULT '0',
  `rewardKillHonor` float NOT NULL DEFAULT '0',
  `startItem` int unsigned NOT NULL DEFAULT '0',
  `flags` int unsigned NOT NULL DEFAULT '0',
  `minimapTargetMark` tinyint unsigned NOT NULL DEFAULT '0',
  `requiredPlayerKills` tinyint unsigned NOT NULL DEFAULT '0',
  `rewardSkillId` smallint unsigned NOT NULL DEFAULT '0',
  `rewardSkillPoints` tinyint unsigned NOT NULL DEFAULT '0',
  `rewardReputationMask` tinyint unsigned NOT NULL DEFAULT '0',
  `questGiverPortrait` int unsigned NOT NULL DEFAULT '0',
  `questTurnInPortrait` int unsigned NOT NULL DEFAULT '0',
  `rewardItem1` int unsigned NOT NULL DEFAULT '0',
  `rewardAmount1` smallint unsigned NOT NULL DEFAULT '0',
  `rewardItem2` int unsigned NOT NULL DEFAULT '0',
  `rewardAmount2` smallint unsigned NOT NULL DEFAULT '0',
  `rewardItem3` int unsigned NOT NULL DEFAULT '0',
  `rewardAmount3` smallint unsigned NOT NULL DEFAULT '0',
  `rewardItem4` int unsigned NOT NULL DEFAULT '0',
  `rewardAmount4` smallint unsigned NOT NULL DEFAULT '0',
  `itemDrop1` int unsigned NOT NULL DEFAULT '0',
  `itemDropQuantity1` smallint unsigned NOT NULL DEFAULT '0',
  `itemDrop2` int unsigned NOT NULL DEFAULT '0',
  `itemDropQuantity2` smallint unsigned NOT NULL DEFAULT '0',
  `itemDrop3` int unsigned NOT NULL DEFAULT '0',
  `itemDropQuantity3` smallint unsigned NOT NULL DEFAULT '0',
  `itemDrop4` int unsigned NOT NULL DEFAULT '0',
  `itemDropQuantity4` smallint unsigned NOT NULL DEFAULT '0',
  `rewardChoiceItemId1` int unsigned NOT NULL DEFAULT '0',
  `rewardChoiceItemQuantity1` smallint unsigned NOT NULL DEFAULT '0',
  `rewardChoiceItemId2` int unsigned NOT NULL DEFAULT '0',
  `rewardChoiceItemQuantity2` smallint unsigned NOT NULL DEFAULT '0',
  `rewardChoiceItemId3` int unsigned NOT NULL DEFAULT '0',
  `rewardChoiceItemQuantity3` smallint unsigned NOT NULL DEFAULT '0',
  `rewardChoiceItemId4` int unsigned NOT NULL DEFAULT '0',
  `rewardChoiceItemQuantity4` smallint unsigned NOT NULL DEFAULT '0',
  `rewardChoiceItemId5` int unsigned NOT NULL DEFAULT '0',
  `rewardChoiceItemQuantity5` smallint unsigned NOT NULL DEFAULT '0',
  `rewardChoiceItemId6` int unsigned NOT NULL DEFAULT '0',
  `rewardChoiceItemQuantity6` smallint unsigned NOT NULL DEFAULT '0',
  `poiContinent` smallint unsigned NOT NULL DEFAULT '0',
  `poiX` float NOT NULL DEFAULT '0',
  `poiY` float NOT NULL DEFAULT '0',
  `poiPriority` int unsigned NOT NULL DEFAULT '0',
  `rewardTitle` tinyint unsigned NOT NULL DEFAULT '0',
  `rewardTalents` tinyint unsigned NOT NULL DEFAULT '0',
  `rewardArenaPoints` smallint unsigned NOT NULL DEFAULT '0',
  `rewardFactionId1` smallint unsigned NOT NULL DEFAULT '0',
  `rewardFactionValue1` int NOT NULL DEFAULT '0',
  `rewardFactionOverride1` int NOT NULL DEFAULT '0',
  `rewardFactionId2` smallint unsigned NOT NULL DEFAULT '0',
  `rewardFactionValue2` int NOT NULL DEFAULT '0',
  `rewardFactionOverride2` int NOT NULL DEFAULT '0',
  `rewardFactionId3` smallint unsigned NOT NULL DEFAULT '0',
  `rewardFactionValue3` int NOT NULL DEFAULT '0',
  `rewardFactionOverride3` int NOT NULL DEFAULT '0',
  `rewardFactionId4` smallint unsigned NOT NULL DEFAULT '0',
  `rewardFactionValue4` int NOT NULL DEFAULT '0',
  `rewardFactionOverride4` int NOT NULL DEFAULT '0',
  `rewardFactionId5` smallint unsigned NOT NULL DEFAULT '0',
  `rewardFactionValue5` int NOT NULL DEFAULT '0',
  `rewardFactionOverride5` int NOT NULL DEFAULT '0',
  `logTitle` text,
  `logDescription` text,
  `questDescription` text,
  `areaDescription` text,
  `questCompletionLog` text,
  `requiredNpcOrGo1` int NOT NULL DEFAULT '0',
  `requiredNpcOrGo2` int NOT NULL DEFAULT '0',
  `requiredNpcOrGo3` int NOT NULL DEFAULT '0',
  `requiredNpcOrGo4` int NOT NULL DEFAULT '0',
  `requiredNpcOrGoCount1` smallint unsigned NOT NULL DEFAULT '0',
  `requiredNpcOrGoCount2` smallint unsigned NOT NULL DEFAULT '0',
  `requiredNpcOrGoCount3` smallint unsigned NOT NULL DEFAULT '0',
  `requiredNpcOrGoCount4` smallint unsigned NOT NULL DEFAULT '0',
  `requiredItemId1` int unsigned NOT NULL DEFAULT '0',
  `requiredItemId2` int unsigned NOT NULL DEFAULT '0',
  `requiredItemId3` int unsigned NOT NULL DEFAULT '0',
  `requiredItemId4` int unsigned NOT NULL DEFAULT '0',
  `requiredItemId5` int unsigned NOT NULL DEFAULT '0',
  `requiredItemId6` int unsigned NOT NULL DEFAULT '0',
  `requiredItemCount1` smallint unsigned NOT NULL DEFAULT '0',
  `requiredItemCount2` smallint unsigned NOT NULL DEFAULT '0',
  `requiredItemCount3` smallint unsigned NOT NULL DEFAULT '0',
  `requiredItemCount4` smallint unsigned NOT NULL DEFAULT '0',
  `requiredItemCount5` smallint unsigned NOT NULL DEFAULT '0',
  `requiredItemCount6` smallint unsigned NOT NULL DEFAULT '0',
  `requiredSpell` int unsigned NOT NULL DEFAULT '0',
  `objectiveText1` text,
  `objectiveText2` text,
  `objectiveText3` text,
  `objectiveText4` text,
  `rewardCurrencyId1` smallint unsigned NOT NULL DEFAULT '0',
  `rewardCurrencyId2` smallint unsigned NOT NULL DEFAULT '0',
  `rewardCurrencyId3` smallint unsigned NOT NULL DEFAULT '0',
  `rewardCurrencyId4` smallint unsigned NOT NULL DEFAULT '0',
  `rewardCurrencyCount1` int unsigned NOT NULL DEFAULT '0',
  `rewardCurrencyCount2` int unsigned NOT NULL DEFAULT '0',
  `rewardCurrencyCount3` int unsigned NOT NULL DEFAULT '0',
  `rewardCurrencyCount4` int unsigned NOT NULL DEFAULT '0',
  `requiredCurrencyId1` smallint unsigned NOT NULL DEFAULT '0',
  `requiredCurrencyId2` smallint unsigned NOT NULL DEFAULT '0',
  `requiredCurrencyId3` smallint unsigned NOT NULL DEFAULT '0',
  `requiredCurrencyId4` smallint unsigned NOT NULL DEFAULT '0',
  `requiredCurrencyCount1` tinyint unsigned NOT NULL DEFAULT '0',
  `requiredCurrencyCount2` tinyint unsigned NOT NULL DEFAULT '0',
  `requiredCurrencyCount3` tinyint unsigned NOT NULL DEFAULT '0',
  `requiredCurrencyCount4` int unsigned NOT NULL DEFAULT '0',
  `questGiverTextWindow` text,
  `questGiverTargetName` text,
  `questTurnTextWindow` text,
  `questTurnTargetName` text,
  `soundAccept` smallint unsigned NOT NULL DEFAULT '890',
  `soundTurnIn` smallint unsigned NOT NULL DEFAULT '878',
  `verifiedBuild` smallint DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `quest_template_addon` (
  `id` int unsigned NOT NULL DEFAULT '0',
  `maxLevel` tinyint unsigned NOT NULL DEFAULT '0',
  `allowableClasses` int unsigned NOT NULL DEFAULT '0',
  `startQuestId` int unsigned NOT NULL DEFAULT '0',
  `specialFlags` tinyint unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `creature_queststarter` (
  `creatureId` mediumint unsigned NOT NULL DEFAULT '0',
  `questId` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`creatureId`, `questId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `creature_questender` (
  `creatureId` mediumint unsigned NOT NULL DEFAULT '0',
  `questId` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`creatureId`, `questId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `gameobject_queststarter` (
  `gameObjectId` int unsigned NOT NULL DEFAULT '0',
  `questId` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`gameObjectId`, `questId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `gameobject_questender` (
  `gameObjectId` int unsigned NOT NULL DEFAULT '0',
  `questId` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`gameObjectId`, `questId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `schema_migrations` (
  `migration` varchar(255) NOT NULL,
  `appliedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`migration`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;