USE `firelands_world`;

CREATE TABLE IF NOT EXISTS `creature_template` (
  `entry` int unsigned NOT NULL DEFAULT '0',
  `difficultyEntry1` int unsigned NOT NULL DEFAULT '0',
  `difficultyEntry2` int unsigned NOT NULL DEFAULT '0',
  `difficultyEntry3` int unsigned NOT NULL DEFAULT '0',
  `killCredit1` int unsigned NOT NULL DEFAULT '0',
  `killCredit2` int unsigned NOT NULL DEFAULT '0',
  `modelId1` int unsigned NOT NULL DEFAULT '0',
  `modelId2` int unsigned NOT NULL DEFAULT '0',
  `modelId3` int unsigned NOT NULL DEFAULT '0',
  `modelId4` int unsigned NOT NULL DEFAULT '0',
  `name` varchar(100) NOT NULL DEFAULT '',
  `femaleName` varchar(100) NOT NULL DEFAULT '',
  `subname` varchar(100) DEFAULT NULL,
  `iconName` varchar(100) DEFAULT NULL,
  `gossipMenuId` int unsigned NOT NULL DEFAULT '0',
  `minLevel` tinyint unsigned NOT NULL DEFAULT '1',
  `maxLevel` tinyint unsigned NOT NULL DEFAULT '1',
  `exp` smallint NOT NULL DEFAULT '0',
  `exp unk` smallint NOT NULL DEFAULT '0',
  `faction` smallint unsigned NOT NULL DEFAULT '0',
  `npcFlag` int unsigned NOT NULL DEFAULT '0',
  `speedWalk` float NOT NULL DEFAULT '1',
  `speedRun` float NOT NULL DEFAULT '1.14286',
  `scale` float NOT NULL DEFAULT '1',
  `rank` tinyint unsigned NOT NULL DEFAULT '0',
  `dmgSchool` tinyint NOT NULL DEFAULT '0',
  `baseAttackTime` int unsigned NOT NULL DEFAULT '0',
  `rangeAttackTime` int unsigned NOT NULL DEFAULT '0',
  `baseVariance` float NOT NULL DEFAULT '1',
  `rangeVariance` float NOT NULL DEFAULT '1',
  `unitClass` tinyint unsigned NOT NULL DEFAULT '0',
  `unitFlags` int unsigned NOT NULL DEFAULT '0',
  `unitFlags2` int unsigned NOT NULL DEFAULT '0',
  `dynamicFlags` int unsigned NOT NULL DEFAULT '0',
  `family` tinyint NOT NULL DEFAULT '0',
  `trainerType` tinyint NOT NULL DEFAULT '0',
  `trainerClass` tinyint unsigned NOT NULL DEFAULT '0',
  `trainerRace` tinyint unsigned NOT NULL DEFAULT '0',
  `type` tinyint unsigned NOT NULL DEFAULT '0',
  `typeFlags` int unsigned NOT NULL DEFAULT '0',
  `typeFlags2` int unsigned NOT NULL DEFAULT '0',
  `lootId` int unsigned NOT NULL DEFAULT '0',
  `pickpocketLoot` int unsigned NOT NULL DEFAULT '0',
  `skinLoot` int unsigned NOT NULL DEFAULT '0',
  `resistance1` smallint NOT NULL DEFAULT '0',
  `resistance2` smallint NOT NULL DEFAULT '0',
  `resistance3` smallint NOT NULL DEFAULT '0',
  `resistance4` smallint NOT NULL DEFAULT '0',
  `resistance5` smallint NOT NULL DEFAULT '0',
  `resistance6` smallint NOT NULL DEFAULT '0',
  `spell1` int unsigned NOT NULL DEFAULT '0',
  `spell2` int unsigned NOT NULL DEFAULT '0',
  `spell3` int unsigned NOT NULL DEFAULT '0',
  `spell4` int unsigned NOT NULL DEFAULT '0',
  `spell5` int unsigned NOT NULL DEFAULT '0',
  `spell6` int unsigned NOT NULL DEFAULT '0',
  `spell7` int unsigned NOT NULL DEFAULT '0',
  `spell8` int unsigned NOT NULL DEFAULT '0',
  `petSpellDataId` int unsigned NOT NULL DEFAULT '0',
  `vehicleId` int unsigned NOT NULL DEFAULT '0',
  `minGold` int unsigned NOT NULL DEFAULT '0',
  `maxGold` int unsigned NOT NULL DEFAULT '0',
  `aiName` varchar(64) NOT NULL DEFAULT '',
  `movementType` tinyint unsigned NOT NULL DEFAULT '0',
  `hoverHeight` float NOT NULL DEFAULT '1',
  `healthModifier` float NOT NULL DEFAULT '1',
  `healthModifierExtra` float NOT NULL DEFAULT '1',
  `manaModifier` float NOT NULL DEFAULT '1',
  `manaModifierExtra` float NOT NULL DEFAULT '1',
  `armorModifier` float NOT NULL DEFAULT '1',
  `damageModifier` float NOT NULL DEFAULT '1',
  `experienceModifier` float NOT NULL DEFAULT '1',
  `racialLeader` tinyint unsigned NOT NULL DEFAULT '0',
  `movementId` int unsigned NOT NULL DEFAULT '0',
  `regenHealth` tinyint unsigned NOT NULL DEFAULT '1',
  `mechanicImmuneMask` int unsigned NOT NULL DEFAULT '0',
  `spellSchoolImmuneMask` int unsigned NOT NULL DEFAULT '0',
  `flagsExtra` int unsigned NOT NULL DEFAULT '0',
  `scriptName` varchar(64) NOT NULL DEFAULT '',
  `verifiedBuild` smallint NOT NULL DEFAULT '0',
  `waypointPathId` int unsigned NOT NULL DEFAULT '0',
  `cyclicSplinePathId` int unsigned NOT NULL DEFAULT '0',
  `mount` int unsigned NOT NULL DEFAULT '0',
  `bytes1` int unsigned NOT NULL DEFAULT '0',
  `bytes2` int unsigned NOT NULL DEFAULT '0',
  `emote` int unsigned NOT NULL DEFAULT '0',
  `aiAnimKit` smallint NOT NULL DEFAULT '0',
  `movementAnimKit` smallint NOT NULL DEFAULT '0',
  `meleeAnimKit` smallint NOT NULL DEFAULT '0',
  `visibilityDistanceType` tinyint unsigned DEFAULT '0',
  `auras` text,
  PRIMARY KEY (`entry`),
  KEY `idx_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `creature` (
  `guid` int unsigned NOT NULL AUTO_INCREMENT,
  `id` int unsigned NOT NULL DEFAULT '0',
  `mapId` smallint unsigned NOT NULL DEFAULT '0',
  `zoneId` smallint unsigned NOT NULL DEFAULT '0',
  `areaId` smallint unsigned NOT NULL DEFAULT '0',
  `spawnMask` int unsigned NOT NULL DEFAULT '1',
  `phaseMask` int unsigned NOT NULL DEFAULT '1',
  `modelId` int unsigned NOT NULL DEFAULT '0',
  `equipmentId` int NOT NULL DEFAULT '0',
  `posX` float NOT NULL DEFAULT '0',
  `posY` float NOT NULL DEFAULT '0',
  `posZ` float NOT NULL DEFAULT '0',
  `orientation` float NOT NULL DEFAULT '0',
  `spawnTimeSecs` int unsigned NOT NULL DEFAULT '120',
  `animTier` tinyint unsigned NOT NULL DEFAULT '0',
  `visibilityDistanceType` tinyint unsigned NOT NULL DEFAULT '0',
  `defaultTplExtendedFlags` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`guid`),
  KEY `idx_id` (`id`),
  KEY `idx_map` (`mapId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `creature_addon` (
  `guid` int unsigned NOT NULL,
  `pathId` bigint unsigned NOT NULL DEFAULT '0',
  `mount` int unsigned NOT NULL DEFAULT '0',
  `bytes1` int unsigned NOT NULL DEFAULT '0',
  `bytes2` int unsigned NOT NULL DEFAULT '0',
  `emote` int unsigned NOT NULL DEFAULT '0',
  `visibilityDistanceType` tinyint unsigned NOT NULL DEFAULT '0',
  `aiAnimKit` smallint unsigned NOT NULL DEFAULT '0',
  `movementAnimKit` smallint unsigned NOT NULL DEFAULT '0',
  `meleeAnimKit` smallint unsigned NOT NULL DEFAULT '0',
  `auras` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`guid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `creature_model_info` (
  `modelId` int unsigned NOT NULL DEFAULT '0',
  `boundingRadius` float NOT NULL DEFAULT '0',
  `combatReach` float NOT NULL DEFAULT '0',
  `displayId` int unsigned NOT NULL DEFAULT '0',
  `nativeXScale` float NOT NULL DEFAULT '1',
  `nativeYScale` float NOT NULL DEFAULT '1',
  `nativeZScale` float NOT NULL DEFAULT '1',
  `worldEffectScale` float NOT NULL DEFAULT '1',
  `groupSoundId` int unsigned NOT NULL DEFAULT '0',
  `footprintRadius` float NOT NULL DEFAULT '0',
  `footprintTexture` varchar(100) DEFAULT NULL,
  `footprintTextureLength` int unsigned NOT NULL DEFAULT '0',
  `modelScale` float NOT NULL DEFAULT '1',
  `ambient` tinyint unsigned NOT NULL DEFAULT '0',
  `creatureGroundShadowScale` float NOT NULL DEFAULT '1',
  `modelIsBot` tinyint unsigned NOT NULL DEFAULT '0',
  `collisionHeight` float NOT NULL DEFAULT '0',
  `collisionWidth` float NOT NULL DEFAULT '0',
  `collisionRadius` float NOT NULL DEFAULT '0',
  PRIMARY KEY (`modelId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `creature_equip_template` (
  `creatureId` int unsigned NOT NULL DEFAULT '0',
  `id` tinyint unsigned NOT NULL DEFAULT '1',
  `itemId1` int unsigned NOT NULL DEFAULT '0',
  `itemId2` int unsigned NOT NULL DEFAULT '0',
  `itemId3` int unsigned NOT NULL DEFAULT '0',
  `verifiedBuild` smallint DEFAULT '0',
  PRIMARY KEY (`creatureId`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `creature_text` (
  `creatureId` int unsigned NOT NULL DEFAULT '0',
  `groupId` tinyint unsigned NOT NULL DEFAULT '0',
  `id` tinyint unsigned NOT NULL DEFAULT '0',
  `text` mediumtext NOT NULL,
  `type` tinyint unsigned NOT NULL DEFAULT '0',
  `language` tinyint NOT NULL DEFAULT '0',
  `probability` float NOT NULL DEFAULT '0',
  `emote` int unsigned NOT NULL DEFAULT '0',
  `duration` int unsigned NOT NULL DEFAULT '0',
  `sound` int unsigned NOT NULL DEFAULT '0',
  `soundType` int unsigned NOT NULL DEFAULT '0',
  `broadcastTextId` int NOT NULL DEFAULT '0',
  `textRange` tinyint unsigned NOT NULL DEFAULT '0',
  `comment` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`creatureId`,`groupId`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `npc_vendor` (
  `entry` int unsigned NOT NULL DEFAULT '0',
  `slot` smallint NOT NULL DEFAULT '0',
  `item` int NOT NULL DEFAULT '0',
  `maxcount` int unsigned NOT NULL DEFAULT '0',
  `incrtime` int unsigned NOT NULL DEFAULT '0',
  `extendedCost` int unsigned NOT NULL DEFAULT '0',
  `type` tinyint unsigned NOT NULL DEFAULT '1',
  `playerConditionId` int NOT NULL DEFAULT '0',
  `verifiedBuild` smallint DEFAULT '0',
  PRIMARY KEY (`entry`, `item`, `extendedCost`, `type`),
  KEY `idx_slot` (`slot`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;