USE `firelands_world`;

INSERT IGNORE INTO `schema_migrations` (`migration`) VALUES
  ('world_schema.sql'),
  ('world_schema_gossip.sql'),
  ('world_schema_quest.sql'),
  ('world_schema_creature.sql'),
  ('world_schema_gameobject.sql'),
  ('world_schema_spell.sql'),
  ('world_schema_player.sql'),
  ('world_seed_quest_data.sql'),
  ('world_seed_quest_template_addon_data.sql'),
  ('world_seed_creature_data.sql'),
  ('world_seed_creature_spawn_data.sql'),
  ('world_seed_creature_addon_data.sql'),
  ('world_seed_creature_model_info_data.sql'),
  ('world_seed_creature_queststarter_data.sql'),
  ('world_seed_creature_questender_data.sql'),
  ('world_seed_creature_template_addon_data.sql'),
  ('world_seed_creature_equip_template_data.sql'),
  ('world_seed_creature_text_data.sql'),
  ('world_seed_npc_vendor_data.sql'),
  ('world_seed_gameobject_data.sql'),
  ('world_seed_gameobject_template_addon_data.sql'),
  ('world_seed_gameobject_spawn_data.sql'),
  ('world_seed_gameobject_addon_data.sql'),
  ('world_seed_gameobject_queststarter_data.sql'),
  ('world_seed_gameobject_questender_data.sql'),
  ('world_seed_gossip_data.sql'),
  ('world_seed_gossip_action_data.sql'),
  ('world_seed_gossip_box_data.sql'),
  ('world_seed_gossip_menu_data.sql'),
  ('world_seed_npc_text_data.sql'),
  ('world_seed_spell_dbc_data.sql'),
  ('world_seed_spelldbc_data.sql'),
  ('world_seed_spell_area_data.sql'),
  ('world_seed_spell_group_data.sql'),
  ('world_seed_spell_group_stack_rules_data.sql'),
  ('world_seed_spell_learn_spell_data.sql'),
  ('world_seed_spell_linked_spell_data.sql'),
  ('world_seed_spell_proc_data.sql'),
  ('world_seed_spell_rank_data.sql'),
  ('world_seed_spell_required_data.sql'),
  ('world_seed_spell_target_position_data.sql'),
  ('world_seed_spelldifficulty_dbc_data.sql'),
  ('world_seed_playercreateinfo_data.sql'),
  ('world_seed_playercreateinfo_action_data.sql'),
  ('world_seed_playercreateinfo_cast_spell_data.sql'),
  ('world_seed_playercreateinfo_item_data.sql'),
  ('world_seed_playercreateinfo_skills_data.sql'),
  ('world_seed_playercreateinfo_spell_custom_data.sql'),
  ('world_seed_player_levelstats_data.sql'),
  ('world_seed_player_xp_for_level_data.sql'),
  ('world_seed_player_racestats_data.sql');

INSERT IGNORE INTO `version` (`coreVersion`, `dbVersion`) VALUES
  ('Firelands 4.3.4.15595', 'Schema 2026-06-01');