USE `firelands_world`;

CREATE TABLE IF NOT EXISTS `gameobject_template` (
  `entry` int unsigned NOT NULL DEFAULT '0',
  `type` tinyint unsigned NOT NULL DEFAULT '0',
  `displayId` int unsigned NOT NULL DEFAULT '0',
  `name` varchar(100) NOT NULL DEFAULT '',
  `iconName` varchar(100) NOT NULL DEFAULT '',
  `castBarCaption` varchar(100) NOT NULL DEFAULT '',
  `unk1` varchar(100) NOT NULL DEFAULT '',
  `size` float NOT NULL DEFAULT '1',
  `data0` int unsigned NOT NULL DEFAULT '0',
  `data1` int NOT NULL DEFAULT '0',
  `data2` int unsigned NOT NULL DEFAULT '0',
  `data3` int unsigned NOT NULL DEFAULT '0',
  `data4` int unsigned NOT NULL DEFAULT '0',
  `data5` int unsigned NOT NULL DEFAULT '0',
  `data6` int NOT NULL DEFAULT '0',
  `data7` int unsigned NOT NULL DEFAULT '0',
  `data8` int unsigned NOT NULL DEFAULT '0',
  `data9` int unsigned NOT NULL DEFAULT '0',
  `data10` int unsigned NOT NULL DEFAULT '0',
  `data11` int unsigned NOT NULL DEFAULT '0',
  `data12` int unsigned NOT NULL DEFAULT '0',
  `data13` int unsigned NOT NULL DEFAULT '0',
  `data14` int unsigned NOT NULL DEFAULT '0',
  `data15` int unsigned NOT NULL DEFAULT '0',
  `data16` int unsigned NOT NULL DEFAULT '0',
  `data17` int unsigned NOT NULL DEFAULT '0',
  `data18` int unsigned NOT NULL DEFAULT '0',
  `data19` int unsigned NOT NULL DEFAULT '0',
  `data20` int unsigned NOT NULL DEFAULT '0',
  `data21` int unsigned NOT NULL DEFAULT '0',
  `data22` int unsigned NOT NULL DEFAULT '0',
  `data23` int unsigned NOT NULL DEFAULT '0',
  `data24` int unsigned NOT NULL DEFAULT '0',
  `data25` int unsigned NOT NULL DEFAULT '0',
  `data26` int unsigned NOT NULL DEFAULT '0',
  `data27` int unsigned NOT NULL DEFAULT '0',
  `data28` int unsigned NOT NULL DEFAULT '0',
  `data29` int unsigned NOT NULL DEFAULT '0',
  `data30` int unsigned NOT NULL DEFAULT '0',
  `data31` int unsigned NOT NULL DEFAULT '0',
  `requiredLevel` int NOT NULL DEFAULT '0',
  `aiName` varchar(64) NOT NULL DEFAULT '',
  `scriptName` varchar(64) NOT NULL DEFAULT '',
  `faction` smallint unsigned NOT NULL DEFAULT '0',
  `flags` int unsigned NOT NULL DEFAULT '0',
  `minGold` int unsigned NOT NULL DEFAULT '0',
  `maxGold` int unsigned NOT NULL DEFAULT '0',
  `artkit0` int NOT NULL DEFAULT '0',
  `artkit1` int NOT NULL DEFAULT '0',
  `artkit2` int NOT NULL DEFAULT '0',
  `artkit3` int NOT NULL DEFAULT '0',
  `artkit4` int NOT NULL DEFAULT '0',
  `verifiedBuild` smallint DEFAULT '0',
  PRIMARY KEY (`entry`),
  KEY `idx_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `gameobject` (
  `guid` int unsigned NOT NULL AUTO_INCREMENT,
  `id` int unsigned NOT NULL DEFAULT '0',
  `mapId` smallint unsigned NOT NULL DEFAULT '0',
  `zoneId` smallint unsigned NOT NULL DEFAULT '0',
  `areaId` smallint unsigned NOT NULL DEFAULT '0',
  `spawnMask` int unsigned NOT NULL DEFAULT '1',
  `phaseMask` int unsigned NOT NULL DEFAULT '1',
  `positionX` float NOT NULL DEFAULT '0',
  `positionY` float NOT NULL DEFAULT '0',
  `positionZ` float NOT NULL DEFAULT '0',
  `orientation` float NOT NULL DEFAULT '0',
  `rotation0` float NOT NULL DEFAULT '0',
  `rotation1` float NOT NULL DEFAULT '0',
  `rotation2` float NOT NULL DEFAULT '0',
  `rotation3` float NOT NULL DEFAULT '0',
  `spawnTimeSecs` int unsigned NOT NULL DEFAULT '120',
  `animTier` tinyint unsigned NOT NULL DEFAULT '0',
  `visibilityDistanceType` tinyint unsigned NOT NULL DEFAULT '0',
  `defaultTplExtendedFlags` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`guid`),
  KEY `idx_id` (`id`),
  KEY `idx_map` (`mapId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `gameobject_addon` (
  `guid` int unsigned NOT NULL,
  `pathId` bigint unsigned NOT NULL DEFAULT '0',
  `mount` int unsigned NOT NULL DEFAULT '0',
  `bytes1` int unsigned NOT NULL DEFAULT '0',
  `bytes2` int unsigned NOT NULL DEFAULT '0',
  `emote` int unsigned NOT NULL DEFAULT '0',
  `visibilityDistanceType` tinyint unsigned NOT NULL DEFAULT '0',
  `aiAnimKit` smallint unsigned NOT NULL DEFAULT '0',
  `movementAnimKit` smallint unsigned NOT NULL DEFAULT '0',
  `meleeAnimKit` smallint unsigned NOT NULL DEFAULT '0',
  `auras` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`guid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;