#!/usr/bin/env python3
"""
Build deployable SQL bundles under sql/bundled/.

When sql/migrations/*.sql files exist: concatenate sql/init + those migrations
(one bundle per firelands_* database). Migration files are ordered by the numeric
prefix before the first '_'.

When migrations/ has no .sql files: leaves sql/bundled/firelands_*.sql unchanged
(edit those files directly); still refreshes zz_seed_schema_migrations.sql from
sql/init (and any migration filenames if present).
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SQL_DIR = REPO_ROOT / "sql"
BUNDLED_DIR = SQL_DIR / "bundled"
INIT_DIR = SQL_DIR / "init"
MIGRATIONS_DIR = SQL_DIR / "migrations"
OUT_DIR = BUNDLED_DIR

HEADER = """-- Generated by tools/merge_migrations.py — do not edit by hand.
-- Regenerate: python3 tools/merge_migrations.py  (or: cmake --build build --target merge-migrations)

"""

KNOWN_DBS = ("firelands_auth", "firelands_characters", "firelands_world")


def migration_sort_key(path: Path) -> tuple[int, str]:
    stem = path.name.split("_", 1)[0]
    try:
        return (int(stem), path.name)
    except ValueError:
        return (10**9, path.name)


def migrator_sql_files() -> list[Path]:
    """Match DatabaseMigrator::MigrateDirectory order: bundled, init, migrations."""
    files: list[Path] = []
    if BUNDLED_DIR.is_dir():
        bundled = [
            p
            for p in BUNDLED_DIR.iterdir()
            if p.is_file() and p.suffix == ".sql" and not p.name.startswith("zz_")
        ]
        bundled.sort(key=lambda p: str(p))
        files.extend(bundled)
    if INIT_DIR.is_dir():
        init = [p for p in INIT_DIR.iterdir() if p.is_file() and p.suffix == ".sql"]
        init.sort(key=lambda p: str(p))
        files.extend(init)
    if MIGRATIONS_DIR.is_dir():
        mig = [p for p in MIGRATIONS_DIR.iterdir() if p.is_file() and p.suffix == ".sql"]
        mig.sort(key=lambda p: str(p))
        files.extend(mig)
    return files


def detect_database(path: Path, content: str) -> str | None:
    m = re.search(r"USE\s+`(firelands_[^`]+)`", content, re.IGNORECASE)
    if m:
        return m.group(1)
    m = re.search(
        r"CREATE\s+DATABASE\s+IF\s+NOT\s+EXISTS\s+`(firelands_[^`]+)`",
        content,
        re.IGNORECASE,
    )
    if m:
        return m.group(1)
    for db in KNOWN_DBS:
        if f"`{db}`." in content:
            return db
    name = path.name.lower()
    if "auth" in name and "character" not in name:
        return "firelands_auth"
    if "item_instance" in name or "characters" in name:
        return "firelands_characters"
    if "world" in name or name.startswith(("5_", "8_", "9_", "10_", "12_", "15_", "16_", "17_", "18_", "19_", "20_", "22_", "23_", "24_", "25_", "26_", "27_world", "29_", "30_", "31_", "32_")):
        return "firelands_world"
    return None


def init_path_for_db(db: str) -> Path | None:
    mapping = {
        "firelands_auth": INIT_DIR / "auth_schema.sql",
        "firelands_characters": INIT_DIR / "characters_schema.sql",
        "firelands_world": INIT_DIR / "world_schema.sql",
    }
    p = mapping.get(db)
    return p if p and p.is_file() else None


def write_seed_only() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    seed_lines = [
        HEADER.rstrip(),
        "-- Marks sql/bundled (except zz_*.sql), sql/init, sql/migrations as applied.",
        "",
        "CREATE DATABASE IF NOT EXISTS `firelands_auth`;",
        "",
        "CREATE TABLE IF NOT EXISTS `firelands_auth`.`schema_migrations` (",
        "  `migration` VARCHAR(255) NOT NULL,",
        "  `applied_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,",
        "  PRIMARY KEY (`migration`)",
        ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;",
        "",
        "INSERT IGNORE INTO `firelands_auth`.`schema_migrations` (`migration`) VALUES",
    ]
    names = [p.name for p in migrator_sql_files()]
    if not names:
        print("WARN: no sql files found for schema_migrations seed.", file=sys.stderr)
        return
    quoted = ",\n".join(f"  ({repr(n)})" for n in names)
    seed_lines.append(quoted + ";")
    seed_path = OUT_DIR / "zz_seed_schema_migrations.sql"
    seed_path.write_text("\n".join(seed_lines) + "\n", encoding="utf-8")
    print(f"Wrote {seed_path.relative_to(REPO_ROOT)} ({len(names)} name(s))")


def write_merged() -> None:
    MIGRATIONS_DIR.mkdir(parents=True, exist_ok=True)
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    migration_files = sorted(
        [p for p in MIGRATIONS_DIR.glob("*.sql") if p.is_file()],
        key=migration_sort_key,
    )

    if not migration_files:
        print(
            "No sql/migrations/*.sql — leaving sql/bundled/firelands_*.sql unchanged "
            "(edit bundled SQL directly). Refreshing seed only.",
            file=sys.stderr,
        )
        write_seed_only()
        return

    bodies: dict[str, list[str]] = {db: [] for db in KNOWN_DBS}

    for path in migration_files:
        text = path.read_text(encoding="utf-8", errors="replace")
        db = detect_database(path, text)
        if db is None or db not in bodies:
            print(f"WARN: could not classify migration {path.name}; skipping.", file=sys.stderr)
            continue
        bodies[db].append(
            f"\n-- === source: migrations/{path.name} ===\n{text.rstrip()}\n"
        )

    for db in KNOWN_DBS:
        init_p = init_path_for_db(db)
        chunks: list[str] = [HEADER]
        if init_p:
            chunks.append(
                f"-- === source: init/{init_p.name} ===\n{init_p.read_text(encoding='utf-8').rstrip()}\n"
            )
        chunks.extend(bodies[db])
        out_path = OUT_DIR / f"{db}.sql"
        out_path.write_text("\n".join(chunks) + "\n", encoding="utf-8")
        print(f"Wrote {out_path.relative_to(REPO_ROOT)} ({out_path.stat().st_size} bytes)")

    write_seed_only()


def main() -> None:
    write_merged()


if __name__ == "__main__":
    main()
