-- Generated by tools/merge_migrations.py — do not edit by hand.
-- Regenerate: python3 tools/merge_migrations.py  (or: cmake --build build --target merge-migrations)
-- Marks sql/bundled (except zz_*.sql) and sql/init as applied.

CREATE DATABASE IF NOT EXISTS `firelands_auth`;

CREATE TABLE IF NOT EXISTS `firelands_auth`.`schema_migrations` (
  `migration` VARCHAR(255) NOT NULL,
  `applied_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`migration`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO `firelands_auth`.`schema_migrations` (`migration`) VALUES
  ('firelands_auth.sql'),
  ('firelands_characters.sql'),
  ('firelands_world.sql'),
  ('firelands_world_creature_ref_import.sql'),
  ('auth_schema.sql'),
  ('characters_schema.sql'),
  ('world_schema.sql'),
  ('world_schema_core.sql');
